# Generated by Django 4.2.9 on 2024-01-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='portuguese_default',
            field=models.BooleanField(blank=True, default=False, help_text='Is Portuguese set as the default language'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='proficiency_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='study_frequency',
            field=models.TextField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='study_frequency_amount',
            field=models.IntegerField(blank=True, help_text='Time in hours', null=True),
        ),
    ]
