# Generated by Django 4.2.9 on 2024-04-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_alter_customuser_portuguese_default_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="daily_activity_goal",
            field=models.IntegerField(
                default=0,
                help_text="Number of minutes the user aims to be active on the site each day",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="daily_question_goal",
            field=models.IntegerField(
                default=0,
                help_text="Number of questions the user aims to answer each day",
            ),
        ),
    ]
