# Generated by Django 4.2.9 on 2024-04-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0003_customuser_daily_activity_goal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="playback_speed",
            field=models.CharField(
                choices=[("normal", "Normal"), ("slow", "Slow"), ("fast", "Fast")],
                default="normal",
                help_text="Preferred audio playback speed",
                max_length=6,
            ),
        ),
    ]
