# Generated by Django 4.2.9 on 2024-03-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("question_type", models.CharField(max_length=255)),
                ("correct_answer", models.CharField(max_length=255)),
            ],
        ),
    ]
