# Generated by Django 4.2.9 on 2024-03-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
