# Generated by Django 4.2.9 on 2024-03-29 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0002_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="mainsite.unit",
            ),
        ),
    ]
