# Generated by Django 4.2.9 on 2024-04-02 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0006_userattempts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("portuguese_word", models.CharField(max_length=255)),
                ("english_translation", models.CharField(max_length=255)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainsite.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
