# Generated by Django 4.2.9 on 2024-04-02 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0007_alter_question_options_word"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainsite.lesson",
            ),
        ),
    ]
