# Generated by Django 4.2.9 on 2024-04-06 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0009_match"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english_usage", models.TextField()),
                ("portuguese_usage", models.TextField()),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="example_usages",
                        to="mainsite.word",
                    ),
                ),
            ],
        ),
    ]
