# Generated by Django 4.2.9 on 2024-04-12 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0012_alter_userattempts_options_userattempts_lesson_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersavedwords",
            name="custom_english",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usersavedwords",
            name="custom_portuguese",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="usersavedwords",
            name="word",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainsite.word",
            ),
        ),
    ]
