# Generated by Django 4.2.9 on 2024-04-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0015_userfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Advanced", "Advanced"),
                ],
                default="Beginner",
                max_length=12,
            ),
        ),
    ]
