# Generated by Django 4.2.9 on 2024-05-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0016_quiz_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="translation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
